package com.atos.concept.persistence;

// Generated Nov 27, 2015 8:59:55 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sketches generated by hbm2java
 */
@Entity
@Table(name = "sketches")
public class Sketches implements java.io.Serializable {

	private Integer id;
	private String name;
	private String url;
	private String imgInBase64;
	private Date creation;
	private int id_project;

	public Sketches() {
	}

	public Sketches(String name, String url, int idProject) {
		this.name = name;
		this.url = url;
		this.id_project = idProject;
	}

	public Sketches(String name, String url, String imgInBase64, Date creation, int idProject) {
		this.name = name;
		this.url = url;
		this.imgInBase64 = imgInBase64;
		this.creation = creation;
		this.id_project = idProject;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false, length = 500)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "imgInBase64")
	public String getImgInBase64() {
		return this.imgInBase64;
	}

	public void setImgInBase64(String imgInBase64) {
		this.imgInBase64 = imgInBase64;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation", length = 19)
	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	@Column(name = "id_project", nullable = false)
	public int getIdProject() {
		return this.id_project;
	}

	public void setIdProject(int idProject) {
		this.id_project = idProject;
	}

}
