package com.atos.concept.persistence;

// Generated Jun 9, 2015 11:48:26 AM by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * StoriesSlides generated by hbm2java
 */
@Entity
@Table(name = "stories_slides")
public class StoriesSlides implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Slides slides;
	private Stories stories;
	private int slideOrder;

	public StoriesSlides() {
	}

	public StoriesSlides(Slides slides, Stories stories, int slideOrder) {
		this.slides = slides;
		this.stories = stories;
		this.slideOrder = slideOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_slide", nullable = false)
	public Slides getSlides() {
		return this.slides;
	}

	public void setSlides(Slides slides) {
		this.slides = slides;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade={CascadeType.PERSIST})
	@JoinColumn(name = "id_story", nullable = false)
	public Stories getStories() {
		return this.stories;
	}

	public void setStories(Stories stories) {
		this.stories = stories;
	}

	@Column(name = "slide_order", nullable = false)
	public int getSlideOrder() {
		return this.slideOrder;
	}

	public void setSlideOrder(int slideOrder) {
		this.slideOrder = slideOrder;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
	
}
