mvn install:install-file -Dfile=commons-codec-1.9.jar -DgroupId=commons-codec -DartifactId=codec -Dversion=1.9 -Dpackaging=jar
mvn install:install-file -Dfile=log4j-api-2.3.jar -DgroupId=log4j-api -DartifactId=api -Dversion=2.3 -Dpackaging=jar
mvn install:install-file -Dfile=commons-lang3-3.4.jar -DgroupId=commons-lang3 -DartifactId=lang3 -Dversion=3.4 -Dpackaging=jar
mvn install:install-file -Dfile=jboss-logging-3.1.3.GA.jar -DgroupId=jboss-logging -DartifactId=logging -Dversion=3.1.3.GA -Dpackaging=jar
mvn install:install-file -Dfile=log4j-1.2.14.jar -DgroupId=log4j-1.2.14.jar -DartifactId=1.2.14.jar -Dversion=1.2.14 -Dpackaging=jar
mvn install:install-file -Dfile=antlr-2.7.7.jar -DgroupId=antlr-2.7.7.jar -DartifactId=2.7.7.jar -Dversion=2.7.7 -Dpackaging=jar
mvn install:install-file -Dfile=cglib-2.2.jar -DgroupId=cglib-2.2.jar -DartifactId=2.2.jar -Dversion=2.2 -Dpackaging=jar
mvn install:install-file -Dfile=asm-3.3.1.jar -DgroupId=asm-3.3.1.jar -DartifactId=3.3.1.jar -Dversion=3.3.1 -Dpackaging=jar
mvn install:install-file -Dfile=mysql-connector-java-5.1.35.jar -DgroupId=mysql-connector -DartifactId=connector -Dversion=5.1.35 -Dpackaging=jar
mvn install:install-file -Dfile=jboss-transaction-api_1.2_spec-1.0.0.Final.jar -DgroupId=jboss-transaction -DartifactId=transaction -Dversion=1.0.0.Final -Dpackaging=jar
mvn install:install-file -Dfile=javassist-3.18.1-GA.jar -DgroupId=javassist-3.18.1 -DartifactId=3.18.1 -Dversion=GA -Dpackaging=jar
mvn install:install-file -Dfile=hibernate-jpa-2.1-api-1.0.0.Final.jar -DgroupId=hibernate-jpa -DartifactId=jpa -Dversion=1.0.0.Final -Dpackaging=jar
mvn install:install-file -Dfile=jandex-1.1.0.Final.jar -DgroupId=jandex-1.1.0.Final.jar -DartifactId=1.1.0.Final.jar -Dversion=1.1.0.Final -Dpackaging=jar
mvn install:install-file -Dfile=slf4j-log4j12-1.5.6.jar -DgroupId=slf4j-log4j12 -DartifactId=log4j12 -Dversion=1.5.6 -Dpackaging=jar
mvn install:install-file -Dfile=xml-apis-1.0.b2.jar -DgroupId=xml-apis -DartifactId=apis -Dversion=1.0.b2 -Dpackaging=jar
mvn install:install-file -Dfile=jstl-1.2.jar -DgroupId=jstl-1.2.jar -DartifactId=1.2.jar -Dversion=1.2 -Dpackaging=jar
mvn install:install-file -Dfile=httpclient-4.5.jar -DgroupId=httpclient-4.5.jar -DartifactId=4.5.jar -Dversion=4.5 -Dpackaging=jar
mvn install:install-file -Dfile=jboss-logging-annotations-1.2.0.Beta1.jar -DgroupId=jboss-logging -DartifactId=logging -Dversion=1.2.0.Beta1 -Dpackaging=jar
mvn install:install-file -Dfile=jta-1.1.jar -DgroupId=jta-1.1.jar -DartifactId=1.1.jar -Dversion=1.1 -Dpackaging=jar
mvn install:install-file -Dfile=slf4j-api-1.5.6.jar -DgroupId=slf4j-api -DartifactId=api -Dversion=1.5.6 -Dpackaging=jar
mvn install:install-file -Dfile=hibernate-core-4.3.6.Final.jar -DgroupId=hibernate-core -DartifactId=core -Dversion=4.3.6.Final -Dpackaging=jar
mvn install:install-file -Dfile=commons-logging-1.1.1.jar -DgroupId=commons-logging -DartifactId=logging -Dversion=1.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=log4j-web-2.0.2.jar -DgroupId=log4j-web -DartifactId=web -Dversion=2.0.2 -Dpackaging=jar
mvn install:install-file -Dfile=ckeditor-java-core-3.5.3.jar -DgroupId=ckeditor-java -DartifactId=java -Dversion=3.5.3 -Dpackaging=jar
mvn install:install-file -Dfile=log4j-core-2.3.jar -DgroupId=log4j-core -DartifactId=core -Dversion=2.3 -Dpackaging=jar
mvn install:install-file -Dfile=httpcore-4.4.1.jar -DgroupId=httpcore-4.4.1.jar -DartifactId=4.4.1.jar -Dversion=4.4.1 -Dpackaging=jar
mvn install:install-file -Dfile=jsch-0.1.53.jar -DgroupId=jsch-0.1.53.jar -DartifactId=0.1.53.jar -Dversion=0.1.53 -Dpackaging=jar
mvn install:install-file -Dfile=dom4j-1.6.1.jar -DgroupId=dom4j-1.6.1.jar -DartifactId=1.6.1.jar -Dversion=1.6.1 -Dpackaging=jar
mvn install:install-file -Dfile=commons-collections-3.2.1.jar -DgroupId=commons-collections -DartifactId=collections -Dversion=3.2.1 -Dpackaging=jar
mvn install:install-file -Dfile=hibernate-commons-annotations-4.0.5.Final.jar -DgroupId=hibernate-commons -DartifactId=commons -Dversion=4.0.5.Final -Dpackaging=jar 
